### ISSUE TITLE
120fps may not run

### ISSUE THREAD

**Issue by RaymondMcGuire** [FoveHMD/UnityDataCollector#1]
Recording rate 70fps is ok,
but when i set it to 120fps and then press the "space", the following error appeared in unity console:
``
get_transform can only be called from the main thread.
Constructors and field initializers will be executed from the loading thread when loading a scene.
Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.
UnityEngine.Component:get_transform(Component)
Fove.Unity.FoveInterface:CalculateGazeRays(Ray&, Ray&, Vector3, Vector3) (at Assets/FoveUnityPlugin/Source/Behaviours/FoveInterface.cs:301)
Fove.Unity.FoveInterface:GetGazeRays_Immediate() (at Assets/FoveUnityPlugin/Source/Behaviours/FoveInterface.cs:533)
FOVERecorder:RecordDatum() (at Assets/FOVE Sample Scripts/FOVERecorder.cs:260)
FOVERecorder:CollectThreadFunc() (at Assets/FOVE Sample Scripts/FOVERecorder.cs:328)
System.Threading.ThreadHelper:ThreadStart()
``
Do you have any advice for solving this problem?
thx

**Comment by jbfove** [comment]
120hz threading issues have been resolved in the latest versions, which are now included as part of the FOVE Unity plugin (under Assets/FoveUnityPlugin/Source/Behaviours/GazeRecorder.cs)
